# Generated by Django 2.1.1 on 2018-09-24 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship', models.CharField(choices=[('Destroyer', 2), ('Submarine', 3), ('Cruiser', 3), ('Battleship', 4), ('Carrier', 5)], max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='game.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ship',
                'verbose_name_plural': 'ships',
            },
        ),
    ]
