# Generated by Django 2.1.1 on 2018-09-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_shipposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipposition',
            name='horizontal',
            field=models.BooleanField(default=True),
        ),
    ]
