# Generated by Django 2.1.1 on 2018-10-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='hit',
            field=models.BooleanField(default=False),
        ),
    ]
