# Generated by Django 2.1.1 on 2018-10-23 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_attack_hit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attack',
            options={'verbose_name': 'attack', 'verbose_name_plural': 'attacks'},
        ),
        migrations.AlterUniqueTogether(
            name='attack',
            unique_together={('game', 'player', 'x', 'y')},
        ),
    ]
