# Generated by Django 2.1.1 on 2018-10-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20181024_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_turn',
            field=models.BooleanField(default=True),
        ),
    ]
