# Generated by Django 2.1.4 on 2018-12-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_game_player_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
